export const constants = {
  clearColor: { r: 0, g: 0.2, b: 0.2, a: 1 },
  zoom: 10,
  lightDirection: { x: 0, y: 4, z: 10 },
  ambientLightAmount: 0.1,
  scapeWidth: 4,
  scapeHeight: 0.8,
  scapeCols: 8,
  scapeRows: 16,
  scapeSpeed: 0.5,
  scapeY: -4.5,
  movement: 0.1,
  disappearingPoint: 20,
  fogDistance: [45, 60],
};
